#!/usr/bin/env python3
from __future__ import annotations
from PySide6.QtGui import QAction
from config import shortcuts

class ActionManager:
    def __init__(self, parent):
        self.parent = parent
        self._create_actions()

    def _create_actions(self):
        self.new = QAction("&Nowy", self.parent)
        self.new.setShortcut(shortcuts.NEW)
        self.open = QAction("&Otworz...", self.parent)
        self.open.setShortcut(shortcuts.OPEN)
        self.save = QAction("&Zapisz", self.parent)
        self.save.setShortcut(shortcuts.SAVE)
        self.save_as = QAction("Zapisz &jako...", self.parent)
        self.save_as.setShortcut(shortcuts.SAVE_AS)
        self.export = QAction("&Eksport", self.parent)
        self.export.setShortcut(shortcuts.EXPORT)
        self.batch = QAction("Konwerter folderu", self.parent)
        self.exit = QAction("&Zakoncz", self.parent)
        self.exit.setShortcut(shortcuts.EXIT)
        self.undo = QAction("&Cofnij", self.parent)
        self.undo.setShortcut(shortcuts.UNDO)
        self.redo = QAction("&Ponow", self.parent)
        self.redo.setShortcut(shortcuts.REDO)
        self.cut = QAction("&Wytnij", self.parent)
        self.cut.setShortcut(shortcuts.CUT)
        self.copy = QAction("&Kopiuj", self.parent)
        self.copy.setShortcut(shortcuts.COPY)
        self.paste = QAction("W&klej", self.parent)
        self.paste.setShortcut(shortcuts.PASTE)
        self.delete = QAction("&Usun", self.parent)
        self.delete.setShortcut(shortcuts.DELETE)
        self.zoom_in = QAction("Powieksz", self.parent)
        self.zoom_in.setShortcut(shortcuts.ZOOM_IN)
        self.zoom_out = QAction("Pomniejsz", self.parent)
        self.zoom_out.setShortcut(shortcuts.ZOOM_OUT)
        self.fit = QAction("Dopasuj", self.parent)
        self.fit.setShortcut(shortcuts.FIT)
        self.actual_size = QAction("100%", self.parent)
        self.actual_size.setShortcut(shortcuts.ACTUAL_SIZE)
        self.crop = QAction("Kadruj", self.parent)
        self.crop.setShortcut(shortcuts.CROP)
        self.spot = QAction("Usun obiekt", self.parent)
        self.brush = QAction("Pedzel korekt", self.parent)
        self.frame = QAction("Ramka", self.parent)
        self.info = QAction("Informacje o zdjeciu", self.parent)
        self.compare = QAction("Porownaj z plikiem...", self.parent)
        self.rotate_left = QAction("Obrot L", self.parent)
        self.rotate_right = QAction("Obrot P", self.parent)
        self.flip_h = QAction("Flip H", self.parent)
        self.flip_v = QAction("Flip V", self.parent)
        self.before_after = QAction("Przed/Po", self.parent)
        self.pencil = QAction("Olowek", self.parent)
        self.black_white = QAction("Czarno-biale", self.parent)
        self.sepia = QAction("Sepia", self.parent)
        self.negative = QAction("Negatyw", self.parent)
        self.vignette = QAction("Winieta", self.parent)
        self.auto_enhance = QAction("Auto-korekta", self.parent)
        self.resize_image = QAction("Zmien rozmiar...", self.parent)
