#!/usr/bin/env python3
from __future__ import annotations
from PySide6.QtGui import QAction
from config import shortcuts
from config.i18n import t, I18n


class ActionManager:
    def __init__(self, parent):
        self.parent = parent
        self._create_actions()
        I18n.get().on_change(self._refresh_texts)

    def _create_actions(self):
        self.new = QAction(t("new"), self.parent)
        self.new.setShortcut(shortcuts.NEW)
        self.open = QAction(t("open"), self.parent)
        self.open.setShortcut(shortcuts.OPEN)
        self.save = QAction(t("save"), self.parent)
        self.save.setShortcut(shortcuts.SAVE)
        self.save_as = QAction(t("save_as"), self.parent)
        self.save_as.setShortcut(shortcuts.SAVE_AS)
        self.export = QAction(t("export"), self.parent)
        self.export.setShortcut(shortcuts.EXPORT)
        self.batch = QAction(t("batch"), self.parent)
        self.exit = QAction(t("exit"), self.parent)
        self.exit.setShortcut(shortcuts.EXIT)
        self.undo = QAction(t("undo"), self.parent)
        self.undo.setShortcut(shortcuts.UNDO)
        self.redo = QAction(t("redo"), self.parent)
        self.redo.setShortcut(shortcuts.REDO)
        self.cut = QAction(t("cut"), self.parent)
        self.cut.setShortcut(shortcuts.CUT)
        self.copy = QAction(t("copy"), self.parent)
        self.copy.setShortcut(shortcuts.COPY)
        self.paste = QAction(t("paste"), self.parent)
        self.paste.setShortcut(shortcuts.PASTE)
        self.delete = QAction(t("delete"), self.parent)
        self.delete.setShortcut(shortcuts.DELETE)
        self.zoom_in = QAction(t("zoom_in"), self.parent)
        self.zoom_in.setShortcut(shortcuts.ZOOM_IN)
        self.zoom_out = QAction(t("zoom_out"), self.parent)
        self.zoom_out.setShortcut(shortcuts.ZOOM_OUT)
        self.fit = QAction(t("fit"), self.parent)
        self.fit.setShortcut(shortcuts.FIT)
        self.actual_size = QAction("100%", self.parent)
        self.actual_size.setShortcut(shortcuts.ACTUAL_SIZE)
        self.crop = QAction(t("crop"), self.parent)
        self.crop.setShortcut(shortcuts.CROP)
        self.spot = QAction(t("spot"), self.parent)
        self.brush = QAction(t("brush"), self.parent)
        self.frame = QAction(t("frame"), self.parent)
        self.info = QAction(t("info"), self.parent)
        self.compare = QAction(t("compare"), self.parent)
        self.rotate_left = QAction(t("rotate_left"), self.parent)
        self.rotate_right = QAction(t("rotate_right"), self.parent)
        self.flip_h = QAction(t("flip_h"), self.parent)
        self.flip_v = QAction(t("flip_v"), self.parent)
        self.before_after = QAction(t("before_after"), self.parent)
        self.pencil = QAction(t("pencil"), self.parent)
        self.black_white = QAction(t("black_white"), self.parent)
        self.sepia = QAction(t("sepia"), self.parent)
        self.negative = QAction(t("negative"), self.parent)
        self.gaussian_blur = QAction(t("blur"), self.parent)
        self.sharpen = QAction(t("sharpen"), self.parent)
        self.emboss = QAction(t("emboss"), self.parent)
        self.vignette = QAction(t("vignette"), self.parent)
        self.auto_enhance = QAction(t("auto_enhance"), self.parent)
        self.resize_image = QAction(t("resize"), self.parent)
        self.overlay = QAction(t("overlay"), self.parent)
        self.straighten = QAction(t("straighten"), self.parent)
        self.watermark = QAction(t("watermark"), self.parent)
        self.check_updates = QAction(t("check_updates"), self.parent)
        self.about = QAction(t("about"), self.parent)
        self.hdr = QAction(t("hdr"), self.parent)
        self.cartoon = QAction(t("cartoon"), self.parent)
        self.glitch = QAction(t("glitch"), self.parent)
        self.thermal = QAction(t("thermal"), self.parent)
        self.pixelate = QAction(t("pixelate"), self.parent)
        self.duotone = QAction(t("duotone"), self.parent)
        self.theme_toggle = QAction(t("theme"), self.parent)
        self.lang_pl = QAction(t("lang_pl"), self.parent)
        self.lang_en = QAction(t("lang_en"), self.parent)
        self.lang_es = QAction(t("lang_es"), self.parent)
        self.shortcuts = QAction(t("shortcuts"), self.parent)
        self.layers = QAction(t("layers"), self.parent)
        self.face_detect = QAction(t("face_detect"), self.parent)
        self.history_timeline = QAction(t("history"), self.parent)

    def _refresh_texts(self, lang=None):
        self.new.setText(t("new"))
        self.open.setText(t("open"))
        self.save.setText(t("save"))
        self.save_as.setText(t("save_as"))
        self.export.setText(t("export"))
        self.batch.setText(t("batch"))
        self.exit.setText(t("exit"))
        self.undo.setText(t("undo"))
        self.redo.setText(t("redo"))
        self.cut.setText(t("cut"))
        self.copy.setText(t("copy"))
        self.paste.setText(t("paste"))
        self.delete.setText(t("delete"))
        self.zoom_in.setText(t("zoom_in"))
        self.zoom_out.setText(t("zoom_out"))
        self.fit.setText(t("fit"))
        self.crop.setText(t("crop"))
        self.spot.setText(t("spot"))
        self.brush.setText(t("brush"))
        self.frame.setText(t("frame"))
        self.info.setText(t("info"))
        self.compare.setText(t("compare"))
        self.rotate_left.setText(t("rotate_left"))
        self.rotate_right.setText(t("rotate_right"))
        self.flip_h.setText(t("flip_h"))
        self.flip_v.setText(t("flip_v"))
        self.before_after.setText(t("before_after"))
        self.pencil.setText(t("pencil"))
        self.black_white.setText(t("black_white"))
        self.sepia.setText(t("sepia"))
        self.negative.setText(t("negative"))
        self.gaussian_blur.setText(t("blur"))
        self.sharpen.setText(t("sharpen"))
        self.emboss.setText(t("emboss"))
        self.vignette.setText(t("vignette"))
        self.auto_enhance.setText(t("auto_enhance"))
        self.resize_image.setText(t("resize"))
        self.overlay.setText(t("overlay"))
        self.straighten.setText(t("straighten"))
        self.watermark.setText(t("watermark"))
        self.check_updates.setText(t("check_updates"))
        self.about.setText(t("about"))
        self.hdr.setText(t("hdr"))
        self.cartoon.setText(t("cartoon"))
        self.glitch.setText(t("glitch"))
        self.thermal.setText(t("thermal"))
        self.pixelate.setText(t("pixelate"))
        self.duotone.setText(t("duotone"))
        self.theme_toggle.setText(t("theme"))
        self.shortcuts.setText(t("shortcuts"))
        self.layers.setText(t("layers"))
        self.face_detect.setText(t("face_detect"))
        self.history_timeline.setText(t("history"))
