#!/usr/bin/env python3
from __future__ import annotations
from PySide6.QtWidgets import QMenuBar

class MenuBar(QMenuBar):
    def __init__(self, parent, actions):
        super().__init__(parent)
        self.actions = actions
        self.setStyleSheet("QMenuBar { background: #252526; color: #CCCCCC; border-bottom: 1px solid #333; } QMenuBar::item:selected { background: #4A9EFF; color: white; } QMenu { background: #252526; color: #CCCCCC; border: 1px solid #444; } QMenu::item:selected { background: #4A9EFF; }")
        self._build()
    def _build(self):
        fm = self.addMenu("&Plik")
        fm.addAction(self.actions.new)
        fm.addAction(self.actions.open)
        fm.addSeparator()
        fm.addAction(self.actions.save)
        fm.addAction(self.actions.save_as)
        self.recent_menu = fm.addMenu("Ostatnio otwierane")
        fm.addSeparator()
        fm.addAction(self.actions.export)
        fm.addSeparator()
        fm.addAction(self.actions.exit)
        em = self.addMenu("&Edycja")
        em.addAction(self.actions.undo)
        em.addAction(self.actions.redo)
        em.addSeparator()
        em.addAction(self.actions.cut)
        em.addAction(self.actions.copy)
        em.addAction(self.actions.paste)
        em.addSeparator()
        em.addAction(self.actions.delete)
        om = self.addMenu("&Obraz")
        om.addAction(self.actions.auto_enhance)
        om.addAction(self.actions.resize_image)
        om.addAction(self.actions.overlay)
        om.addAction(self.actions.straighten)
        om.addAction(self.actions.watermark)
        om.addSeparator()
        om.addAction(self.actions.info)
        film = self.addMenu("&Filtry")
        film.addAction(self.actions.pencil)
        film.addAction(self.actions.black_white)
        film.addAction(self.actions.sepia)
        film.addAction(self.actions.negative)
        film.addAction(self.actions.vignette)
        film.addAction(self.actions.frame)
        vm = self.addMenu("&Widok")
        vm.addAction(self.actions.zoom_in)
        vm.addAction(self.actions.zoom_out)
        vm.addSeparator()
        vm.addAction(self.actions.fit)
        vm.addAction(self.actions.actual_size)
        vm.addSeparator()
        vm.addAction(self.actions.compare)
        tm = self.addMenu("&Narzedzia")
        tm.addAction(self.actions.crop)
        tm.addAction(self.actions.spot)
        tm.addAction(self.actions.rotate_left)
        tm.addAction(self.actions.rotate_right)
        tm.addAction(self.actions.flip_h)
        tm.addAction(self.actions.flip_v)
        pm = self.addMenu("&Pomoc")
        pm.addAction(self.actions.check_updates)
        pm.addSeparator()
        pm.addAction(self.actions.about)
